//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HospitalManagementSystem.Resources.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string activeGrid {
            get {
                return ResourceManager.GetString("activeGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string adminCardButton {
            get {
                return ResourceManager.GetString("adminCardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create departments, assign rooms and manage capacities..
        /// </summary>
        internal static string adminDepartmentsContent {
            get {
                return ResourceManager.GetString("adminDepartmentsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments and Rooms.
        /// </summary>
        internal static string adminDepartmentsTitle {
            get {
                return ResourceManager.GetString("adminDepartmentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and manage Nurses, Surgeons, Doctors, Lab Workers and Administrators..
        /// </summary>
        internal static string adminManageProfilesContent {
            get {
                return ResourceManager.GetString("adminManageProfilesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User Profiles.
        /// </summary>
        internal static string adminManageProfilesTitle {
            get {
                return ResourceManager.GetString("adminManageProfilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage drug catalog and stock  across departments..
        /// </summary>
        internal static string adminMedicationsContent {
            get {
                return ResourceManager.GetString("adminMedicationsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medications Inventory.
        /// </summary>
        internal static string adminMedicationsTitle {
            get {
                return ResourceManager.GetString("adminMedicationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Console.
        /// </summary>
        internal static string adminTitle {
            get {
                return ResourceManager.GetString("adminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register and maintain ambulances and other vehicles..
        /// </summary>
        internal static string adminVehiclesContent {
            get {
                return ResourceManager.GetString("adminVehiclesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        internal static string adminVehiclesTitle {
            get {
                return ResourceManager.GetString("adminVehiclesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Dashboard.
        /// </summary>
        internal static string backToDashboard {
            get {
                return ResourceManager.GetString("backToDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string brandGrid {
            get {
                return ResourceManager.GetString("brandGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancelBtn {
            get {
                return ResourceManager.GetString("cancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        internal static string capacityGrid {
            get {
                return ResourceManager.GetString("capacityGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string codeGrid {
            get {
                return ResourceManager.GetString("codeGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Department.
        /// </summary>
        internal static string createDepartment {
            get {
                return ResourceManager.GetString("createDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Room.
        /// </summary>
        internal static string createRoom {
            get {
                return ResourceManager.GetString("createRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current patients (optional).
        /// </summary>
        internal static string currentPatientsOptional {
            get {
                return ResourceManager.GetString("currentPatientsOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string deleteBtn {
            get {
                return ResourceManager.GetString("deleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department (optional).
        /// </summary>
        internal static string departmentBox {
            get {
                return ResourceManager.GetString("departmentBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        internal static string departmentNameBox {
            get {
                return ResourceManager.GetString("departmentNameBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        internal static string departmentsTitle {
            get {
                return ResourceManager.GetString("departmentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admit a patient to a room..
        /// </summary>
        internal static string doctorAdmissionContent {
            get {
                return ResourceManager.GetString("doctorAdmissionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Admission.
        /// </summary>
        internal static string doctorAdmissionTitle {
            get {
                return ResourceManager.GetString("doctorAdmissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review completed lab test results..
        /// </summary>
        internal static string doctorLaboratoryContent {
            get {
                return ResourceManager.GetString("doctorLaboratoryContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratory results.
        /// </summary>
        internal static string doctorLaboratoryTitle {
            get {
                return ResourceManager.GetString("doctorLaboratoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse and view patient medical records..
        /// </summary>
        internal static string doctorMedicalRecordsContent {
            get {
                return ResourceManager.GetString("doctorMedicalRecordsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Medical Records.
        /// </summary>
        internal static string doctorMedicalRecordsTitle {
            get {
                return ResourceManager.GetString("doctorMedicalRecordsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new prescription for a patient..
        /// </summary>
        internal static string doctorPrescriptionContent {
            get {
                return ResourceManager.GetString("doctorPrescriptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Prescription.
        /// </summary>
        internal static string doctorPrescriptionTitle {
            get {
                return ResourceManager.GetString("doctorPrescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See past and scheduled surgeries..
        /// </summary>
        internal static string doctorSurgeriesContent {
            get {
                return ResourceManager.GetString("doctorSurgeriesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View surgeries.
        /// </summary>
        internal static string doctorSurgeriesTitle {
            get {
                return ResourceManager.GetString("doctorSurgeriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Console.
        /// </summary>
        internal static string doctorTitle {
            get {
                return ResourceManager.GetString("doctorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string editBtn {
            get {
                return ResourceManager.GetString("editBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string emailBox {
            get {
                return ResourceManager.GetString("emailBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string fullName {
            get {
                return ResourceManager.GetString("fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        internal static string headGrid {
            get {
                return ResourceManager.GetString("headGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head of department.
        /// </summary>
        internal static string headOfDepartment {
            get {
                return ResourceManager.GetString("headOfDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Service.
        /// </summary>
        internal static string lastServiceGrid {
            get {
                return ResourceManager.GetString("lastServiceGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string loginBtn {
            get {
                return ResourceManager.GetString("loginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string nameGrid {
            get {
                return ResourceManager.GetString("nameGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string newBtn {
            get {
                return ResourceManager.GetString("newBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Department.
        /// </summary>
        internal static string newDepartmentBtn {
            get {
                return ResourceManager.GetString("newDepartmentBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Room.
        /// </summary>
        internal static string newRoomBtn {
            get {
                return ResourceManager.GetString("newRoomBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string notesBox {
            get {
                return ResourceManager.GetString("notesBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string numberGrid {
            get {
                return ResourceManager.GetString("numberGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string passwordBox {
            get {
                return ResourceManager.GetString("passwordBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string patientName {
            get {
                return ResourceManager.GetString("patientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string patientPhone {
            get {
                return ResourceManager.GetString("patientPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UMCN:.
        /// </summary>
        internal static string patientUmcn {
            get {
                return ResourceManager.GetString("patientUmcn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string phoneBox {
            get {
                return ResourceManager.GetString("phoneBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate.
        /// </summary>
        internal static string plateGrid {
            get {
                return ResourceManager.GetString("plateGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string roleGrid {
            get {
                return ResourceManager.GetString("roleGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room number.
        /// </summary>
        internal static string roomNumber {
            get {
                return ResourceManager.GetString("roomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        internal static string roomsGrid {
            get {
                return ResourceManager.GetString("roomsGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string saveBtn {
            get {
                return ResourceManager.GetString("saveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search patient (name).
        /// </summary>
        internal static string searchPatient {
            get {
                return ResourceManager.GetString("searchPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string typeGrid {
            get {
                return ResourceManager.GetString("typeGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        internal static string userDetails {
            get {
                return ResourceManager.GetString("userDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string usernameBox {
            get {
                return ResourceManager.GetString("usernameBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string usernameGrid {
            get {
                return ResourceManager.GetString("usernameGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Details.
        /// </summary>
        internal static string vehicleDetails {
            get {
                return ResourceManager.GetString("vehicleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        internal static string vehiclesTitle {
            get {
                return ResourceManager.GetString("vehiclesTitle", resourceCulture);
            }
        }
    }
}
